sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
- bash install.sh
script:
- source env.sh && npm run test
notifications:
  slack: devops-training-spb:kfjTXFxdFQxyBbAJ0UtYVqOe
deploy:
  provider: heroku
  app: mighty-ravine-42598
  api_key:
    secure: bHJDAa1Br6X0USwQGVMM9uvGByu0H2LqHLgsfCDVg+oYe18+iAiRacbxM7APuMzHRQkB1YJ/ljUo//P69jdyeeMF1iBrZdLJsRdym5iJwb3hsVPZSCDCDks2g6m+AmEeHp/oZErXuHF5FTKFLXRezfc3MekQ7r7j47d2DdZCJtIfSFeK1bGQLefNMfPcfIPGPdlxcbefv1TYAe52cf2em7W1Q+uc9jL/zAcSVCHc6sUzoUvDkLnEtt8WuGqicDO/2AU2ixrfqvbiK/ghrHcku5AquImA8c/e4HRlkpGxNqQI4vGAK91GEg790j4sR3cqJMYXdwzMJbOseLM2rTKdl0aTsXKoCDV8lLjKE5doDx7LT0ZR8SsZc9+yvtVw49Y8MdB3govuEmpTQdM1N75h9LmrhNUGdS6WjEG8srPZowMZcQA6Afe/4BFQ2iZIQhKCyalPhu7Xepxdfaumntt+BkqzSengxQXQanui1Rwmdozvn3XjXqUZWsMnviSdqvDXVZ/6p/ITeyq/je+o2f82hlsAK2nZmY3cRiX5nQUaNm//f4EpGAGLNPIo8eSB/HJLoTshsUp8z61gKfocrT78v9bpnIh/RlF7kCwY6iEdr0DVT9XwOM9ASkyO/1RCKJ1FK/qA9JGPcY0zhm8XUBaZydJYz1fN5kdZHAjUUt0nhrQ=
